[tool.black]
line-length = 120
target-version = ['py39']
experimental_string_processing = true

[tool.isort]
profile = 'black'
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 100

[tool.mypy]
[[tool.mypy.overrides]]
module = [
    "pydantic.*"
]
ignore_missing_imports = true
